---
title: "Econ 108-05"
output: html_document
date: '2022-11-04'
---

1.
a)
browser <- read.csv("web-browsers.csv")
linreg <- glm(log(spend)~broadband+anychildren, data=browser)
summary(linreg)

2.
a)
email <- read.csv("spam.csv")
full <- glm(word_george ~ ., data=email, family=binomial)
1 - full$deviance/full$null.deviance
b)
pvals <- summary(full)$coef[-1,4]
hist(pvals, xlab="p-value", main="", col="lightblue")
c)
fdr_cut <- function(pvals, q=0.1){
  pvals <- sort(pvals[!is.na(pvals)])
  N <- length(pvals)
  k <- rank(pvals, ties.method="min")
  alpha <- max(pvals[ pvals<= (q*k/(N+1)) ])
  plot(pvals, log="xy", xlab="order", main=sprintf("FDR of %g",q),
   ylab="p-value", bty="n", col=c(8,2)[(pvals<=alpha) + 1], pch=20)
  lines(1:N, q*(1:N)/(N+1))
  dev.off()
  return(alpha)
}
fdr_cut(pvals)
d)
( signif <- which(pvals <= 0.005297195 ) )
cut <- glm(word_george ~ ., data=email[,c("word_george", names(signif))], family="binomial")
1 - cut$deviance/cut$null.deviance
e)
cutvar=c("word_george", names(signif))

## Out of sample prediction experiment
## first, define the deviance and R2 functions

## pred must be probabilities (0<pred<1) for binomial
deviance <- function(y, pred, family=c("gaussian","binomial")){
	family <- match.arg(family)
	if(family=="gaussian"){
		return( sum( (y-pred)^2 ) )
	}else{
		if(is.factor(y)) y <- as.numeric(y)>1
		return( -2*sum( y*log(pred) + (1-y)*log(1-pred) ) )
	}
}

## get null devaince too, and return R2
R2 <- function(y, pred, family=c("gaussian","binomial")){
	fam <- match.arg(family)
	if(fam=="binomial"){
		if(is.factor(y)){ y <- as.numeric(y)>1 }
	}
	dev <- deviance(y, pred, family=fam)
	dev0 <- deviance(y, mean(y), family=fam)
	return(1-dev/dev0)
}

# setup the experiment
n <- nrow(SC) # the number of observations
K <- 10 # the number of `folds'
# create a vector of fold memberships (random order)
foldid <- rep(1:K,each=ceiling(n/K))[sample(1:n)]
# create an empty dataframe of results
OOS <- data.frame(full=rep(NA,K), cut=rep(NA,K)) 
# use a for loop to run the experiment
for(k in 1:K){ 
	train <- which(foldid!=k) # train on all but fold `k'
		
	## fit the two regressions
	rfull <- glm(word_george~., data=email, subset=train, family=binomial)
	rcut <- glm(word_george~., data=email[,cutvar], subset=train, family=binomial)

	## get predictions: type=response so we have probabilities
	predfull <- predict(rfull, newdata=email[-train,], type="response")
	predcut <- predict(rcut, newdata=email[-train,], type="response")

	## calculate and log R2
	OOS$full[k] <- R2(y=email$word_george[-train], pred=predfull, family="binomial")
	OOS$cut[k] <- R2(y=email$word_george[-train], pred=predcut, family="binomial")

	## print progress
	cat(k, " ")
}
## plot it in plum
par(mai=c(.9,.9,.1,.1))
boxplot(OOS, col="plum", ylab="R2", xlab="model", bty="n")

## what are the average OOS R2?
colMeans(OOS) # WOW!  Full model really sucks.

f)
null <- glm(word_george~1, data=email)
system.time(fwd <- step(null, scope=formula(full), dir="forward"))
length(coef(fwd))